services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./assets:/app/assets
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: portfolio-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./assets:/app/assets